### ISSUE TITLE
In Sec 3.2, what is B(CC[F])?

### ISSUE THREAD

**Issue by benediktahrens** [DanGrayson/VV-C-system-from-a-monad#29]
- In the introduction, B(CC[F]) seems to be the B-component of a B-system (B,\tilde B), i.e., a Nat-indexed family of sets.
- In Sec 3.2, it seems to be a (unital pre-) B-system, since an isomorphism to B(CC,F) is promised.

Which one is it?

**Comment by DanGrayson** [comment]
Here is one of those:

<img width="822" alt="Screen Shot 2021-10-06 at 3 12 15 PM" src="https://user-images.githubusercontent.com/700228/136276238-399ead1f-ed28-41d6-b034-c51f4d6cd47e.png">

**Comment by DanGrayson** [comment]
We'll make the B-systems have a boldface B, since that is what VV does i https://www.math.ias.edu/Voevodsky/files/files-annotated/Dropbox/Unfinished_papers/Type_systems/Notes_on_Type_Systems/Bsystems/B_systems_current.pdf
