### ISSUE TITLE
Bibliography needs updating?

### ISSUE THREAD

**Issue by benediktahrens** [DanGrayson/VV-C-system-from-a-monad#38]
- [17] contains a warning that might be better positioned at the spot where [17] is cited.
- [21] was never published, and was later redone to result in https://doi.org/10.4230/LIPIcs.FSCD.2019.6.
- [25] has been published, one could use the bibtex entry below
- [35] title needs capitalization
- [45] is it published?
- [51] is it published? author order?

```
@article{kapulkin2021simplicial,
	title={The simplicial model of Univalent Foundations (after Voevodsky)},
	author={Kapulkin, Krzysztof and Lumsdaine, Peter LeFanu},
	journal={Journal of the European Mathematical Society},
	volume={23},
	number={6},
	pages={2071--2126},
	year={2021},
	doi={10.4171/jems/1050}
}
```

**Comment by DanGrayson** [comment]
Thanks!  I've addressed these remarks.

**Comment by DanGrayson** [comment]
[45] is another paper I should try to get published, unless it's too unfinished.
