### ISSUE TITLE
Spelling of X-sorted

### ISSUE THREAD

**Issue by benediktahrens** [DanGrayson/VV-C-system-from-a-monad#8]
There are multiple spellings of "X-sorted" in the paper. Examples are:
- 2-sorted
- two-sorted
- two sorted
- multi sorted

My suggestion would be to use "two-sorted" and "multi-sorted". It is probably best to search "sorted" and unify. (There is also 1-sorted, for instance.)

**Comment by DanGrayson** [comment]
I have a slight preference for "2-sorted" over "two-sorted", as it conveys more quickly to the brain that 2 is a number.
